title: Avisos aos navegantes
description: Novidades e avisos importantes sobre ônibus e trânsito na Grande Vitória/ES
social_link: twitter
social_username: jamacedo
github_repo: meu_destino_news
github_username: jamacedo
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /meu_destino_news
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
